apiVersion: apps/v1
kind: Deployment
metadata:
  name: vie-deployment
  labels:
    app: vie
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vie
  template:
    metadata:
      labels:
        app: vie
    spec:
      containers:
      - name: vie-app
        image: verifiable-intelligence-engine:1.0.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
        env:
        - name: MODEL_DIR
          value: "/app/models"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 15
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: vie-service
spec:
  selector:
    app: vie
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer